### ISSUE TITLE
Check the segment about local nuget packages

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/developer-docs#9]
This part of debugging documentation has been merged without extensive review and should be checked once.

**Comment by rwmcintosh** [comment]
Points for discussion (I missed the PR, sorry)

- we might remove this section since we have a superior way 
https://github.com/Open-Systems-Pharmacology/developer-docs/blob/187611d230066d44255a1bb597224cec0faa9b2e/NET-specifics/debugging.md?plain=1#L17

- Is the correct image referenced. The preview shows some markup in the text? 
https://github.com/Open-Systems-Pharmacology/developer-docs/blob/187611d230066d44255a1bb597224cec0faa9b2e/NET-specifics/debugging.md?plain=1#L33
![image](https://github.com/Open-Systems-Pharmacology/developer-docs/assets/261477/865d53cc-1371-4aff-a7a9-507dc293960a)


- There's another step missing because you have to reference the local repository in Visual Studio
https://github.com/Open-Systems-Pharmacology/developer-docs/blob/187611d230066d44255a1bb597224cec0faa9b2e/NET-specifics/debugging.md?plain=1#L46
